name: ci workflow
on: [push, pull_request]
jobs:
  compile_job:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@master
      - name: Set up JDK 1.12
        uses: actions/setup-java@master
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn clean compile -DskipTests